Bmerketo/ViewModels/LoginViewModel.cs
namespace Bmerketo.ViewModels;

public class LoginViewModel
{
    public string Email { get; set; } = null!;
    public string Password { get; set; } = null!;
    public bool RememberMe { get; set; } = false;
}

Bmerketo/ViewModels/RegisterViewModel.cs
using Bmerketo.Models.Entities;

namespace Bmerketo.ViewModels;

public class RegisterViewModel
{
    public string FirstName { get; set; } = null!;
    public string LastName { get; set; } = null!;
    public string Email { get; set; } = null!;
    public string Password { get; set; } = null!;

    public static implicit operator UserEntity(RegisterViewModel model)
    {
        return new UserEntity
        {
            FirstName = model.FirstName,
            LastName = model.LastName,
            Email = model.Email,
            UserName = model.Email,
        };
    }
}

Bmerketo/ViewModels/ShowCaseViewModel.cs
namespace Bmerketo.ViewModels;

public class ShowCaseViewModel
{
    public string? Ingress { get; set; } 
    public string? Title { get; set; } 
    public string? LinkContent { get; set; } 
    public string? LinkUrl { get; set; }
    public string? ImageUrl { get; set; } 
}

Bmerketo/Controllers/ContactController.cs
using Bmerketo.Helpers.Repositories;
using Bmerketo.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Bmerketo.Controllers;

public class ContactController : Controller
{
    private readonly ContactFormRepository _formRepository;

    public ContactController(ContactFormRepository formRepository)
    {
        _formRepository = formRepository;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Index(ContactFormViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            await _formRepository.AddAsync(viewModel);
            return RedirectToAction("Index");
        }

        return View(viewModel);
    }

}

Bmerketo/Controllers/LoginController.cs
using Bmerketo.Helpers.Services;
using Bmerketo.Models.Entities;
using Bmerketo.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Bmerketo.Controllers
{
    public class LoginController : Controller
    {
        private readonly AuthenticationService _authenticationService;
        private readonly UserManager<UserEntity> _userManager;
        private readonly SignInManager<UserEntity> _signInManager;

        public LoginController(
            AuthenticationService authenticationService,
            UserManager<UserEntity> userManager,
            SignInManager<UserEntity> signInManager)
        {
            _authenticationService = authenticationService;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(viewModel.Email, viewModel.Password, viewModel.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    var user = await _userManager.FindByEmailAsync(viewModel.Email);
                    var roles = await _userManager.GetRolesAsync(user!);

                    if (roles.Contains("Admin"))
                    {
                        return RedirectToAction("Index", "Admin");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }

                ModelState.AddModelError("", "Incorrect email or password");
            }

            return View(viewModel);
        }
    }
}

Bmerketo/Controllers/RegisterController.cs
using Bmerketo.Helpers.Services;
using Bmerketo.Models.Entities;
using Bmerketo.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bmerketo.Controllers;

public class RegisterController : Controller
{
    private readonly UserManager<UserEntity> _userManager;
    private readonly AuthenticationService _authenticationService;

    public RegisterController(UserManager<UserEntity> userManager, AuthenticationService authenticationService)
    {
        _userManager = userManager;
        _authenticationService = authenticationService;
    }


    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Index(RegisterViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            if (!await _userManager.Users.AnyAsync(x => x.Email == viewModel.Email))
            {
                if (await _authenticationService.RegisterAsync(viewModel))
                    return RedirectToAction("Index", "Login");
            }
            
            ModelState.AddModelError("", "User with the same email address aleady exists");
            
        }

        return View(viewModel);
    }
}

Bmerketo/Views/Partials/_ContactForm.cshtml
@model ContactFormViewModel

<div class="contactform">
    <h2 class="contact-title">Get in Touch</h2>
<form asp-action="Index" asp-controller="Contact" method="post" novalidate>
    <div asp-validation-summary=ModelOnly class="text-danger"></div>

    <div class="contact-info">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control" onkeyup="validateText(event)" />
        <span asp-validation-for="Name" class="small text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" type="email" class="form-control" onkeyup="validateEmail(event)"  />
        <span asp-validation-for="Email" class="small text-danger"></span>
    </div>
    </div>
    <div class="mb-3">
        <label asp-for="Message" class="form-label">Message</label>
        <textarea asp-for="Message" class="form-control" onkeyup="validateText(event)" rows="7"></textarea>
        <span asp-validation-for="Message" class="small text-danger"></span>
    </div>

    <div class="d-grid mt-5">
        <button type="submit" class="btn-theme">SEND</button>
    </div>
</form>
</div>

Bmerketo/Views/Partials/_FeaturedProducts.cshtml
@inject ProductRepository productRepo;

<div class="category-container featured">
    <h1>Featured tents</h1>

    <div class="products-container">
        @foreach (var product in await productRepo.GetAllAsync())
        {   
            if (product.ProductCategories.Any(x => x.Category.CategoryName == "featured"))
            {
                <div class"product-item">
                    <div>
                        <a asp-controller="products" asp-action="details" asp-route-id="@product.ArticleNumber">
                            <img src="/images/tents/@product.ImageUrl" />
                        </a>
                    </div>
                    <div><a asp-controller="products" asp-action="details" asp-route-id="@product.ArticleNumber">@product.Title</a></div>
                    <div id="price">$ @product.Price</div>
                </div>
            }
        }
    </div>
</div>

Bmerketo/Views/Partials/_Footer.cshtml
    <footer>
        <div class="container">
            © @DateTime.Now.Year bmerketo. All right reserved.
        </div>
    </footer>

Bmerketo/Views/Partials/_Header.cshtml
@inject SignInManager<UserEntity> signInManager
@using Microsoft.AspNetCore.Identity

<header>
    <div class="container">
        <div class="logo">
            <a class="logo-link" asp-action="Index" asp-controller="Home">
                <img src="~/images/logo.svg" alt="">bmerketo
            </a>
        </div>
        <nav id="menu" class="menu-links">
            <a class="link" asp-controller="home" asp-action="index">HOME</a>
            <a class="link" asp-controller="products" asp-action="index">PRODUCTS</a>
            <a class="link" asp-controller="contact" asp-action="index">CONTACT</a>
        </nav>
        <nav class="menu-icons">
            @if (signInManager.IsSignedIn(User))
            {
                if (User.IsInRole("Admin"))
                {
                    <a class="link" asp-controller="admin" asp-action="index">Backoffice</a>
                }
                else
                {
                    <a class="link" asp-controller="userprofile" asp-action="index"><i class="fa-solid fa-user"></i></a>


                }

                <a class="link" asp-controller="logout" asp-action="index">Logout</a>

            }
            else
            {
                <a class="link" asp-controller="login" asp-action="index">Login</a>
            }
        </nav>
        <div class="toggle">
            <button class="btn-toggle btn-outline-white" data-option="toggle" data-target="#menu">
                <i id="icon" class="fa-regular fa-bars"></i>
            </button>
        </div>
    </div>
</header>

Bmerketo/Views/Partials/_Login.cshtml
@model LoginViewModel

<div class="login-form">
    <h2 class="login-title">Login to Your Account</h2>
    <form asp-action="Index" asp-controller="Login" method="post" novalidate>
    <div asp-validation-summary=ModelOnly class="text-danger"></div>

    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" type="email" class="form-control" onkeyup="validateEmail(event)" />
        <span asp-validation-for="Email" class="small text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Password" class="form-label">Password</label>
        <input asp-for="Password" type="password" class="form-control" onkeyup="validatePassword(event)" />
        <span asp-validation-for="Password" class="small text-danger"></span>
    </div>

    <div class="d-grid mt-5">
        <button type="submit" class="btn-theme">LOG IN</button>
    </div>
</form>
<div class="register-link">
    <span>Not a member yet?</span>
    <a class="link" asp-controller="register" asp-action="index">Register now</a>
</div>
</div>

Bmerketo/Views/Partials/_Messages.cshtml
@inject ContactFormRepository contactFormRepo;

<h1>Messages</h1>

<div class="messages-container">
    @foreach (var message in await contactFormRepo.GetAllAsync())
    {
        <div class="message-item">
            <div>@message.Email</div>
            <div>@message.Name</div>
            <div>@message.Message</div>
        </div>
    }
</div>

Bmerketo/Views/Partials/_NewProducts.cshtml
@inject ProductRepository productRepo;

<div class="category-container">
    <h1>New tents</h1>

    <div class="products-container">
        @foreach (var product in await productRepo.GetAllAsync())
        {
            if (product.ProductCategories.Any(x => x.Category.CategoryName == "new"))
            {
                <div class"product-item">
                    <div>
                        <a asp-controller="products" asp-action="details" asp-route-id="@product.ArticleNumber">
                            <img src="/images/tents/@product.ImageUrl" />
                        </a>
                    </div>
                    <div><a asp-controller="products" asp-action="details" asp-route-id="@product.ArticleNumber">@product.Title</a></div>
                    <div id="price">$ @product.Price</div>
                </div>
            }
        }
    </div>
</div>

Bmerketo/Views/Partials/_PopularProducts.cshtml
@inject ProductRepository productRepo;

<div class="category-container">
    <h1>Popular tents</h1>

    <div class="products-container">
        @foreach (var product in await productRepo.GetAllAsync())
        {
            if (product.ProductCategories.Any(x => x.Category.CategoryName == "popular"))
            {
                <div class"product-item">
                    <div>
                        <a asp-controller="products" asp-action="details" asp-route-id="@product.ArticleNumber">
                            <img src="/images/tents/@product.ImageUrl" />
                        </a>
                    </div>
                    <div><a asp-controller="products" asp-action="details" asp-route-id="@product.ArticleNumber">@product.Title</a></div>
                    <div id="price">$ @product.Price</div>
                </div>
            }
        }
    </div>
</div>

Bmerketo/Views/Partials/_Register.cshtml
@model RegisterViewModel

<div class="register-form">
    <h2 class="register-title">Create Your Account</h2>
    <form asp-action="Index" asp-controller="Register" method="post" novalidate>
        <div asp-validation-summary=ModelOnly class="text-danger"></div>

        <div class="register-info mb-3">
            <div class="register-field">
                <label asp-for="FirstName" class="form-label">First Name</label>
                <input asp-for="FirstName" class="form-control" onkeyup="validateText(event)" />
                <span asp-validation-for="FirstName" class="small text-danger"></span>
            </div>
            <div class="register-field">
                <label asp-for="LastName" class="form-label">Last Name</label>
                <input asp-for="LastName" class="form-control" onkeyup="validateText(event)" />
                <span asp-validation-for="LastName" class="small text-danger"></span>
            </div>
        </div>

        <div class="register-info mb-3">
            <div class="register-field">
                <label asp-for="Email" class="form-label">Email</label>
                <input asp-for="Email" type="email" class="form-control" onkeyup="validateEmail(event)" />
                <span asp-validation-for="Email" class="small text-danger"></span>
            </div>
            <div class="register-field">
                <label asp-for="Password" class="form-label">Password</label>
                <input asp-for="Password" type="password" class="form-control" onkeyup="validatePassword(event)" />
                <span asp-validation-for="Password" class="small text-danger"></span>
            </div>
        </div>

        <div class="d-grid mt-5">
            <button type="submit" class="btn-theme">SUBMIT</button>
        </div>
    </form>
</div>

Bmerketo/Views/Partials/_Showcase.cshtml
@inject ShowCaseService showcaseService
@{
    var showcase = await showcaseService.GetLatest();
}

@if(showcase != null)
{
    <section class="showcase">
        <div class="container">
            <div class="content">
                <div class="ingress">@showcase?.Ingress</div>
                <div class="title">@showcase?.Title</div>

                @if (!string.IsNullOrEmpty(showcase?.Button?.Url) && !string.IsNullOrEmpty(showcase?.Button?.Content))
                {
                    <a href="@showcase?.Button?.Url" class="btn-theme">@showcase?.Button?.Content</a>
                }
            </div>
            <div class="content-image">
                <img src="~/images/tents/@showcase?.ImageUrl" alt="@showcase?.Title">
            </div>
        </div>
    </section>
}